image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf 
    - make clean
  script: 
    - make strip
  artifacts:
    paths:
      - /bin/ush-debug
      - /bin/ush-bin

# run tests using the binary built before
test:
  stage: test
  script:
    - /bin/ush-bin --help
